name = "PatientEventVectorStudy"
authors = ["Jacob S. Zelko"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
FunSQL = "cf6cc811-59f4-4a10-b258-a8547a8f6407"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OHDSIAPI = "43fe992b-71c2-425c-b13e-efb1498069b1"
OHDSICohortExpressions = "b1469e29-13af-4897-a4a9-3c363a260582"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CSV = "0.10"
DBInterface = "2.6"
DataFrames = "1.8"
DataStructures = "0.19"
Documenter = "1.15"
DrWatson = "2.19.1"
DuckDB = "1.4.1"
FunSQL = "0.14, 0.15"
JSON3 = "1.14"
OHDSICohortExpressions = "0.2"
julia = "1.11.7"
